### ISSUE TITLE
Fragile pages on the Mathy website

### ISSUE THREAD

**Issue by justindujardin** [FragileTech/fragile#92]
I finally got around to publishing some content on the Mathy site dedicated to the integration with Fragile! 🎉 

I added an Examples category and a page with tests/examples using Fragile to solve arbitrary mathy tasks and generate training datasets: https://mathy.ai/examples/swarm/

I also added a link to the Fragile github to the about page: https://mathy.ai/about/#fragile

If you'd like to suggest improvements or corrections to either of those pages, I'd welcome them 🙂

**Comment by Guillemdb** [comment]
It looks really cool! I will take a closer after work to see if I can make any useful suggestion. 

I am planning to also add some more tutorials to `fragile`. Would you be ok if I use `mathy` as an example of how to adapt `fragile` to different environments?  The almost-like-plangym structure of mathy envs makes them the perfect candidate for the example.

Btw I just saw that here `swarm.env._env._env.mathy.print_history(best_state)` I am missing something. A user shouldn't need to do all this introspection. Do you have any suggestion to make the underlying environments easier to access? I will also think about it myself.

**Comment by justindujardin** [comment]
Hey @Guillemdb sorry for the delay, I haven't been working on the mathy solvers any more since I integrated the fragile swarm. I see you're improving the StepSwarm some more recently, I'll have to check it out again in the future :) 

I'd love if you use mathy in your examples! 💯 If there's anything I've done in mathy that could be changed to better align with gym envs, I'm open to that as well. I never put much effort into the gym envs other than as a slim wrapper, since Mathy has its own env classes underlying them.

About the `env._env._env` business 😅 maybe you could have a calculated property? Like

```python
@property
def unwrapped(self):
   return self._env
```

You'd probably need a special case for when envs are wrapped multiple times (like for parallel runners) but then the code you mentioned could look more like:
```python
swarm.env.unwrapped.mathy.print_history(best_state)
```
